openapi: 3.0.1
info:
  version: 0.4.0
  title: MediaWiki PDF Render Service
  description: A service for rendering HTML to PDFs
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: the Wikimedia Services team
    url: http://mediawiki.org/wiki/Services
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
x-default-params:
  domain: en.wikipedia.org
paths:
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
      description: Gets robots.txt
      responses:
        200:
          $ref: '#/components/responses/success'
        default:
          $ref: "#/components/responses/problem"
      x-monitor: false

  /:
    get:
      tags:
        - Root
      description: The root service end-point
      responses:
        200:
          $ref: '#/components/responses/success'
        default:
          $ref: "#/components/responses/problem"
      x-amples:
        - title: spec from root
          request:
            query:
              spec: true
          response:
            status: 200

  # from routes/info.js
  /_info:
    get:
      tags:
        - Root
      description: Gets information about the service.
      responses:
        200:
          $ref: '#/components/responses/success'
        default:
          $ref: "#/components/responses/problem"
      x-amples:
        - title: retrieve service info
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
              description: /.+/
              version: /.+/
              home: /.+/
  /_info/name:
    get:
      tags:
        - Service information
      description: Gets the name of the service
      responses:
        200:
          $ref: '#/components/responses/success'
        default:
          $ref: "#/components/responses/problem"
      x-amples:
        - title: retrieve service name
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
  /_info/version:
    get:
      tags:
        - Service information
      description: Gets the running version of the service
      responses:
        200:
          $ref: '#/components/responses/success'
        default:
          $ref: "#/components/responses/problem"
      x-amples:
        - title: retrieve service version
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              version: /.+/
  /_info/home:
    get:
      tags:
        - Service information
      description: Redirects to the home page
      responses:
        301:
          description: Redirects to the home page
      x-amples:
        - title: redirect to the home page
          request: {}
          response:
            status: 301

  /{domain}/v1/pdf/{title}/{format}/{type}:
    get:
      tags:
        - PDF Rendering
      description: Generates a PDF for the article with the given title in the given format
      parameters:
        - in: path
          name: domain
          schema:
            type: string
          required: true
          description: 'Wikipedia domain including language subdomain - example: en.wikipedia.org'
        - in: path
          name: title
          schema:
            type: string
          required: true
          description: Title of the article we want to generate PDF for
        - in: path
          name: format
          schema:
            type: string
            enum: ['a4', 'letter', 'legal']
          required: true
          description: PDF format
        - in: path
          name: type
          schema:
            type: string
            enum: ['mobile', 'desktop']
            default: desktop
          description: PDF type - `mobile` (optimized for reading on mobile devices) or `desktop` (regular PDF). `desktop` is the default render mode and it will used if param `type` is not passed
      responses:
        200:
          description: A PDF was rendered successfully
          content:
            application/pdf:
              schema:
                type: file
        404:
          description: The specified article was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPError"
        500:
          description: A response is unavailable because server encountered an internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPError"
        503:
          description: A response is unavailable because service queue is busy or full
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPError"
      x-amples:
        - title: Print the Foo page from en.wp.org in letter format
          request:
            params:
              title: Foo
              format: letter
              type: desktop
          response:
            status: 200
            headers:
              content-type: application/pdf
              content-disposition: download; filename="Foo.pdf"; filename*=UTF-8''Foo.pdf
        - title: Print the Bar page from en.wp.org in A4 format using optimized for reading on mobile devices
          request:
            params:
              title: Bar
              format: a4
              type: mobile
          response:
            status: 200
            headers:
              content-type: application/pdf
              content-disposition: download; filename="Bar.pdf"; filename*=UTF-8''Bar.pdf
        - title: Respond file not found for a nonexistent title
          request:
            params:
              title: Nonexistent_title
              format: letter
          response:
            status: 404
            headers:
              content-type: application/json
            schema:
              type: object
              properties:
                name: HTTPError
                status: 404
                message: '404'
                details: Article 'Nonexistent_title' not found
        - title: Respond bad request for an unsupported format
          request: {}
          response:
            status: 404 # FIX: this should return a 400. See T186127.
            headers:
              content-type: text/html # FIX: use application/json. See T186127.

components:
  responses:
    problem:
      description: Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/problem'
    success:
      description: Success
  schemas:
    HTTPError:
      type: object
      properties:
        name:
          type: string
          description: Error type, usually HTTPError
        status:
          type: integer
          description: HTTP Error code
        message:
          type: string
          description: Error type, usually error code
        details:
          type: string
          description: Error details
      required:
        - name
        - status
        - message
    # A https://tools.ietf.org/html/draft-nottingham-http-problem
    problem:
      required:
        - type
      properties:
        status:
          type: integer
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        method:
          type: string
        uri:
          type: string

